### ISSUE TITLE
Create basic Terraform deployment that uses Nix

### ISSUE THREAD

**Issue by robinbb** [LeapYear/sparkle#51]
Create a set of Terraform-based source files to be used to create/destroy a Nix-based server which builds this repo, runs a basic sanity test. Achieve the same thing that is achieved by building the Dockerfile, except without Docker.

**Comment by robinbb** [comment]
WIP at branch 'robinbb/nixify-build' - helps with `nix-build`, the provisioning part of the above.

**Comment by aspiwack** [comment]
@robinbb proposal uploaded at branch [poc/terraform](https://github.com/LeapYear/sparkle/tree/poc/terraform).

**Comment by robinbb** [comment]
@aspiwack I have uploaded some changes to 'poc/terraform'. Please take a look. Also, can you make the SG tighter?

**Comment by aspiwack** [comment]
Regarding your change identification, I tend to prefer profile-based selection (using the name of the profiles from `.aws/credentials`) rather than copy-pasting the credentials into the `terraform.tfvars`.

I've changed the inbound traffic rule to accept only ssh and mosh (as an example of two different inbound rules).
